### PR TITLE
MP1-5191: Fixed bug MPEMaker fails to save plugindependencies: remove handler when done

### PR DESCRIPTION
**Pull request by andrewjswan**

### CODE REVIEW

**Comment by doskabouter** [comment]
I added a new commits to the https://github.com/MediaPortal/MediaPortal-1/tree/MP1-5191_MPEMaker_fails_to_save_plugindependencies branche...

**Comment by andrewjswan** [comment]
> I added a new commits

I dont see it, last commit https://github.com/MediaPortal/MediaPortal-1/commit/74633e92bdc4fcc1012bf4b97616fc92feef50e9
And it merged to Test8

**Comment by doskabouter** [comment]
That is indeed the correct one. If that is indeed included, we should be good

**Comment by andrewjswan** [comment]
> If that is indeed included, we should be good

Test 8 commit - https://github.com/MediaPortal/MediaPortal-1/commit/a42d890e5f5d028bebaa4a73c500dfd3f513b703

**Pull request merged**
