### PR TITLE
Allow other plugins reading the next PS wakeup time

### PR DESCRIPTION
**Pull request by pikim**
Having the ability to do so my USB device would be able to wake the PC at the according time. By connecting the device to the PCs power button it can even wake from S5.

Device schematics and firmware sources will follow.

For a detailed feature list see http://forum.team-mediaportal.com/threads/is-there-any-use-for-a-multi-protocol-ir-receiver-transmitter.129216/

### CODE REVIEW

**Comment by Sebastiii** [comment]
@michael--t :)

**Comment by regeszter** [comment]
I think it is ok.

**Comment by andrewjswan** [comment]
@Sebastiii this changes actual or not?

**Comment by andrewjswan** [comment]
@Sebastiii Maybe it's worth a close? I understand the changes are already in the maser. :)

**Comment by pikim** [comment]
> @Sebastiii Maybe it's worth a close? I understand the changes are already in the maser. :)

No, the changes have never been merged into the master or they were removed again.

**Comment by andrewjswan** [comment]
Jira created, Branch created, PR moved to https://github.com/MediaPortal/MediaPortal-1/pull/196

**Pull request closed without merging**
