### PR TITLE
Mp1 4841 duplicate filenames with different lettercasing

### PR DESCRIPTION
**Pull request by doskabouter**

### CODE REVIEW

**Comment by andrewjswan** [comment]
I think better merge this to master using Github Because Windows can delete both files regardless of Casing ...
@Azzuro @Sebastiii How do you think?

**Comment by andrewjswan** [comment]
May be need create new 1.25_Test1 branch, merge to it this changes and than merge all other branches :)

**Comment by doskabouter** [comment]
I would vote for merging this into master.
Chances of breaking things without noticing is 0%, and it's quite a headache (at least for me) to merge it into a different branch...

**Comment by andrewjswan** [comment]
How about 1.25Pre Test1? Anyway, he will then fall into the master ...

**Comment by andrewjswan** [comment]
I found correct branch with its changes ... https://github.com/MediaPortal/MediaPortal-1/tree/MP1-4841_fix_duplicate_filenames_with_different_lettercasing/mediaportal/MediaPortal.Base
Its merged to 1.25Pre?

**Comment by doskabouter** [comment]
No, I tried to merge in my branch, but failed in that...

**Comment by andrewjswan** [comment]
May be better in one Commit delete all from this files, and in other commit add need files?

**Comment by doskabouter** [comment]
No need to add stuff, only delete the duplicate ones

**Comment by andrewjswan** [comment]
If this works, then yes, otherwise it’s easier to delete all duplicates and originals, and then add the originals.

**Pull request merged**
