### PR TITLE
Fixed exceptions

### PR DESCRIPTION
**Pull request by doskabouter**
…been separated from its underlying RCW cannot be used.

Fixed AreEqual: URI formats are not supported.
Fixed File not Found
Fixed RefreshRate failed: Thread was being aborted.

### CODE REVIEW

**Comment by doskabouter** [comment]
More fixes could be added if I encounter them

**Comment by Azzuro** [comment]
Thank you, about refreshrate need to be very tested, because can break a lot.
@sebastiii

**Comment by doskabouter** [comment]
> 
> 
> Thank you, about refreshrate need to be very tested, because can break a lot.
> @Sebastiii

I disagree.
I verified that at that line currentthread is indeed equal to _workerthread, so the only thing that happens is that that thread aborts itself just before it would end normally.

**Comment by andrewjswan** [comment]
Look like good! And it’s not like it can break something. We can include this in the 1.24 Final and check ...
@Sebastiii :)

**Comment by Azzuro** [comment]
Nope for this release, at least not the for the refreshrate change.
I remember Sebastiii done something about releasing thread because the thread don't stop  or take many times on few users.

I'm agree for next release, with more test delay.

**Comment by doskabouter** [comment]
Ok, fine with me.
It's not that this is critical and I hope I get more exceptions I can fix after more testing is done

**Comment by andrewjswan** [comment]
Need add this Branch/Pull request to 1.25Pre topic in forum ...

**Comment by Azzuro** [comment]
Need to create jira ticket if not already done.

**Comment by doskabouter** [comment]
https://issues.team-mediaportal.com/browse/MP1-4987

**Comment by doskabouter** [comment]
still waiting for others to check their logs for errors tough

**Comment by andrewjswan** [comment]
Better remake PR to https://github.com/MediaPortal/MediaPortal-1/tree/MP1-4987_Fix_exceptions  branch in Mediaportal repo, and after that commit changes directly to it :)

**Comment by doskabouter** [comment]
I have merged the latest commits in my fix_exception branch in mediaportal's fix_exceptionbranch

**Pull request closed without merging**
