### PR TITLE
Fixes detection media info

### PR DESCRIPTION
**Pull request by yartat**
@Sebastiii 
- Update MediaInfo to 0.7.83 (MP-1-MediaInfoLib package 1.0.1) 
- Add "Unknown" language that used in some .ts files
- Add Stream analyzes to BaseTSReaderPlayer and StreamBufferPlayer9

### CODE REVIEW

**Comment by Sebastiii** [comment]
Are you able to recreate the patch against latest master ? There is a conflict in VideoPlayerVMR7.cs (when i merge master to the branch).

**Comment by yartat** [comment]
@Sebastiii , not a problem, I will this evening.

**Comment by yartat** [comment]
I merged with current master branch

**Comment by Sebastiii** [comment]
Thank you :)

**Comment by andrewjswan** [comment]
> I merged with current master branch

Are you able to recreate the patch against latest master ? We try build this branch (based on 1.22Pre) and test it in Area 51 :)

**Comment by andrewjswan** [comment]
And may be update MediaInfo to latests version :)

**Comment by andrewjswan** [comment]
And may be add 3D detection and HDR detection ;)

**Comment by andrewjswan** [comment]
MP1-4777 Merged to 1.23Pre

**Pull request closed without merging**
